variable "ami" {}
variable "keypair" {}
variable "nexus-sg" {}
variable "subnet_id" {}
variable "elb-subnets" {}
variable "cert-arn" {}
variable "nr-key" {}
variable "nr-acc-id" {}
variable "nr-region" {}
variable "name" {}