variable "ami-redhat" {}
variable "ansible-sg" {}
variable "key-name" {}
variable "subnet-id" {}
variable "name" {}
variable "staging-MyPlaybook" {}
variable "prod-MyPlaybook" {}
variable "staging-discovery-script" {}
variable "prod-discovery-script" {}
variable "private_key" {}
variable "nexus-ip" {}
variable "nr-key" {}
variable "nr-acc-id" {}
variable "nr-region" {}